version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management  # 使用带有管理界面的版本
    container_name: im-rabbitmq
    ports:
      - "5672:5672"   # 应用连接端口
      - "15672:15672" # 管理控制台端口
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq # 数据持久化挂载
    restart: always