server:
  port: 8080 # Web 端口

spring:
  servlet:
    multipart:
      max-file-size: 10MB      # 单个文件大小限制
      max-request-size: 50MB   # 单次请求总大小限制
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # 👈 加上这一行，解决 Swagger 启动报错
  datasource:
    # 确保你本地安装了MySQL，并且创建了名为 simple_im 的数据库
    url: jdbc:mysql://localhost:3306/simple_im?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root      # 你的数据库账号
    password: 123456 # ❗❗这里改成你的数据库密码❗❗
    driver-class-name: com.mysql.cj.jdbc.Driver

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    # 开启发送确认机制 (保证消息一定到了 MQ，面试加分项)
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual  # 开启手动确认模式
        concurrency: 4            # 开启 5 个消费者线程同时处理 (并发优化)
        max-concurrency: 12
        retry:
          enabled: true          # 开启消费者重试
          max-attempts: 3        # 最大重试次数 (包含第一次)
          initial-interval: 1000ms # 第一次重试间隔 1秒
          multiplier: 2.0        # 间隔倍数 (1s -> 2s -> 4s)
          max-interval: 10000ms  # 最大间隔

# Netty 配置
netty:
  port: 8888  # WebSocket 端口
  url: /im
#mybatis-plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 控制台打印SQL
  global-config:
    db-config:
      id-type: auto  # 主键策略

# 日志配置
logging:
  level:
    # 设置我们的mapper接口为DEBUG，这样会打印SQL语句
    com.shixun.simpleimserver.mapper: debug
    # 设置MyBatis的核心包为WARN，这样就不会打印连接信息等
    org.apache.ibatis: warn
    # 设置Spring的JDBC包为WARN
    org.springframework.jdbc: warn

# 自定义文件配置
file:
  # ❗请根据你的电脑修改这个路径 (Windows示例: D:/im_uploads/ , Mac/Linux: /data/im_uploads/)
  # 注意：文件夹必须先存在，或者代码里要写自动创建逻辑
  upload-path: D:/im_uploads/
  # 映射的访问前缀 (浏览器访问 http://localhost:8080/files/...)
  access-path: /files/**

